# Generated by Django 5.2.1 on 2025-06-03 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turismo', '0002_categoria'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Categoria',
        ),
        migrations.AddField(
            model_name='pontoturistico',
            name='categoria',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
